In [1]:
import numpy as np

data = np.load(r'C:\Users\moham\Downloads\2026_geoai_arctic_challenge_v1.0\competition_release\train\images\train_000001.npz')
print(f"Arrays:{data}")
for key in data.files:
    arr = data[key]
    print(f"key :{key} , shape: {arr.shape}") 
print(len(data[key][0][0]))

Arrays:NpzFile 'C:\\Users\\moham\\Downloads\\2026_geoai_arctic_challenge_v1.0\\competition_release\\train\\images\\train_000001.npz' with keys: image
key :image , shape: (159, 289, 8)
8


In [22]:
print(arr[: , : , 0].shape)

(159, 289)


In [ ]:
matrix =[
     [[1,2] , [3,4] , [1,2] , [3,4]],
     [[5,6] ,  [7,8] , [1,2] , [3,4]],
     [[9,6] ,  [7,8] , [1,2] , [3,4]]
] # multichannel data 
arr = np.array(matrix)
print(f"matrix shape : {arr.shape}")
print(len(matrix))

matrix shape : (3, 4, 2)
3


In [46]:
matrix =  [[1,2] , [3,4] , [1,2] , [3,4]]
arr = np.array(matrix)
print(f"matrix shape : {arr.shape}")
print(len(matrix[:][:]))

matrix shape : (4, 2)
4


In [24]:
import numpy as np
from PIL import Image

In [27]:
def stretch(a, lo=2, hi=98):
    '''Percentile-stretch each channel of an HWC array into [0, 1]; NaNs become 0.'''
    out = np.zeros(a.shape, dtype=np.float32)
    print(out)
    for i in range(a.shape[-1]):
        print(i)
        ch = a[..., i]
        print(ch)
        vmin, vmax = np.nanpercentile(ch, [lo, hi])
        print(vmin , vmax)
        scaled = (ch - vmin) / (vmax - vmin + 1e-8)
        print(scaled)
        out[..., i] = np.nan_to_num(np.clip(scaled, 0, 1), nan=0.0)
        print(out)

    return out


In [28]:
data  = np.load(r'C:\Users\moham\Downloads\2026_geoai_arctic_challenge_v1.0\competition_release\train\images\train_000001.npz')

print(f"keys in npz file: {data.files}")

image_array = data["image"]

rgb_raw = image_array[... , [0,1,2]]
rgb_stretched =stretch(rgb_raw)


rgb_8bit = (rgb_stretched * 255).astype(np.uint8)


img = Image.fromarray(rgb_8bit.astype("uint8"))
img.save("train_000001.jpg")


keys in npz file: ['image']
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
0
[[190. 190. 181. ... 177. 162. 161.]
 [186. 174. 174. ... 168. 164. 164.]
 [174. 159. 160. ... 156. 156. 172.]
 ...
 [155. 150. 130. ... 101. 147. 147.]
 [147. 147. 126. ... 121. 153. 158.]
 [136. 131. 124. ... 139. 158. 149.]]
24.0 201.0
[[0.93785311 0.93785311 0.88700565 ... 0.86440678 0.77966102 0.7740113 ]
 [0.91525424 0.84745763 0.84745763 ... 0.81355932 0.79096045 0.79096045]
 [0.84745763 0.76271186 0.76836158 ... 0.74576271 0.74576271 0.